adv_cbv/adv_cbv/urls.py
from django.contrib import admin
from django.urls import path,include
from trial import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('trial.urls',namespace="trial"))
]

adv_cbv/trial/urls.py
from django.urls import path,include
from trial import views
app_name="trial"
urlpatterns = [
    path("",views.SchoolListView.as_view(),name="list"),
    path('detail/<int:pk>',views.SchoolDetailView.as_view(),name="detail"),
    path('create/',views.SchoolCreateView.as_view(),name="create"),
    path('update/<int:pk>',views.SchoolUpdateView.as_view(),name="update"),
    path('delete/<int:pk>',views.SchoolDeleteView.as_view(),name="delete")

]

adv_cbv/trial/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class School(models.Model):
    name=models.CharField(max_length=256)
    principal=models.CharField(max_length=256)
    location=models.CharField(max_length=256)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        # return reverse("trial:detail", kwargs={"pk": self.pk})
         return reverse("trial:list")
    
    
class Student(models.Model):
    name=models.CharField(max_length=256)
    age=models.PositiveIntegerField()
    school=models.ForeignKey(School,related_name="rn_students",on_delete=models.CASCADE)

    def __str__(self):
        return self.name

adv_cbv/trial/views.py
from django.shortcuts import render
from trial.models import School,Student
from django.views.generic import View,TemplateView,DetailView,ListView,CreateView,UpdateView,DeleteView
from django.urls import reverse,reverse_lazy
# Create your views here.

class SchoolListView(ListView):
    context_object_name="schools"
    print("HII")
    # ListView returns the list named school_list(default name) we can assign by context_object_name
    model=School
    print(model,ListView)
    # template_name="trial/school_list.html" # default school_list.html if present don't mention this
class SchoolDetailView(DetailView):
    context_object_name="school_detail"
    # DetailView returns the object named schools(default name) we can assign by context_object_name
    model=School
    template_name="trial/school2.html" # default school_detail.html if present don't mention this
class SchoolCreateView(CreateView):
    fields=("name","principal","location")
    model=School
class SchoolUpdateView(UpdateView):
    fields=("name","principal")
    model=School
class SchoolDeleteView(DeleteView):
    context_object_name="school_del"
    model=School
    # template_name="trial/school_confirm_delete.html"
    success_url=reverse_lazy("trial:list")

adv_cbv/adv_cbv/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <style>
        body {
            overflow-x: hidden;
        }
    </style>
</head>

<body class="bg-gradient"
    style="background: linear-gradient(to right,rgba(147, 202, 184, 0.979),rgba(60, 82, 75, 0.979));">
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top" id="navbar" style="background-color:rgba(0, 0, 0, 0.089);">
        <a class="navbar-brand" href="#">
            <img src="./logo-PhotoRoom.png-PhotoRoom.png" width="200" height="40" class="d-inline-block align-top"
                alt="">
        </a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'trial:list' %}">School</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            {% comment %} <li class="nav-item">
                <a class="nav-link" href="website.html">Contact Us</a>
            </li> {% endcomment %}
        </ul>
    </nav>
        <div class="container">
            {% block body_block %}
            {% endblock body_block %}
        </div>


     
    <script>
        let handlescroll=()=>{
            document.getElementById("navbar").style.backgroundColor="rgba(60, 82, 75, 0.979)";
           

        }
        window.addEventListener("scroll",handlescroll)
    </script>
</body>

</html>

adv_cbv/trial/templates/trial/school2.html
{% extends "trial/trial_base.html" %}
    {% block 'body_block' %}
    <div class="jumbotron">
        <h1>School Details :</h1>
        <h3>Name: {{school_detail.name}}</h3>
        <h3>Principal: {{school_detail.principal}}</h3>
        <h3>Location: {{school_detail.location}}</h3>
        <a class='btn btn-primary' href="{% url 'trial:update' pk=school_detail.pk %}">UPDATE</a>
        <a class='btn btn-danger' href="{% url 'trial:delete' pk=school_detail.pk %}">DELETE</a>


        <h1>Students:</h1>
        {% for i in school_detail.rn_students.all %}
        <h3>Name: {{i.name}}</h3>
        <h3>Age: {{i.age}}</h3>
        {% endfor %}    


    {% endblock 'body_block' %}
</div>

adv_cbv/trial/templates/trial/school_confirm_delete.html
{% extends "trial/trial_base.html" %}

{% block 'body_block' %}
<h1>  Delete {{school_del.name}} ?</h1>
        <form action="" method="post">
            {% csrf_token %}
            <input class='btn btn-danger' type="submit" value="Delete">
        </form>
        <a  class='btn btn-primary' href="{% url 'trial:detail' pk=school_del.pk %}">Cancel</a>

{% endblock 'body_block' %} 

adv_cbv/trial/templates/trial/school_form.html
{% extends "trial/trial_base.html" %}

{% block 'body_block' %}
    {% if not form.instance.pk %}
        <h1>Create School</h1>
    {% else %}
        <h1>Update School</h1>
    {% endif %}
    <div class="jumbotron">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit">
        </form>                                        
    </div>


{% endblock 'body_block' %}

adv_cbv/trial/templates/trial/school_list.html
{% extends "trial/trial_base.html" %}

 {% block 'body_block'  %}
    <h1>List of Schools</h1>
    <ol>
        {% for i in schools %}
            <h2><li><a href="{% url 'trial:detail' i.id %}">{{i.name}}</a></li></h2>
            {% comment %} <a class='btn btn-primary' href="{% url 'trial:update' pk=i.id%}">UPDATE</a> {% endcomment %}
            {% comment %} <h2><li>{{i.principal}}</li></h2> {% endcomment %}

        {% endfor %}

    </ol>
   
 
 {% endblock 'body_block' %}

adv_cbv/trial/templates/trial/trial_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <style>
        body {
            overflow-x: hidden;
        }
    </style>
</head>

<body class="bg-gradient"
    style="background: linear-gradient(to right,rgba(147, 202, 184, 0.979),rgba(60, 82, 75, 0.979));">
    <nav class="navbar navbar-expand-sm navbar-light fixed-top" id="navbar" style="background-color:rgba(0, 0, 0, 0.089);">
        <a class="navbar-brand" href="#">
            <img src="./logo-PhotoRoom.png-PhotoRoom.png" width="200" height="40" class="d-inline-block align-top"
                alt="">
        </a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'trial:list' %}">School</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            {% comment %} <li class="nav-item">
                <a class="nav-link" href="{% url 'trial:detail' %}">Contact Us</a>
            </li> {% endcomment %}
        </ul>
    </nav>
        <div class="container">
            <p>HII</p>
            {% block 'body_block' %}
            {% endblock 'body_block' %}
        </div>


     
    <script>
        let handlescroll=()=>{
            document.getElementById("navbar").style.backgroundColor="rgba(60, 82, 75, 0.979)";
           

        }
        window.addEventListener("scroll",handlescroll)
    </script>
</body>

</html>